In [1]:
from scipy import sparse

def gen_rand_sparse_mat(m, n, density):
    M = sparse.rand(m, n, density=density)
    M.data[:] = 1
    return M

X = gen_rand_sparse_mat(10, 10, 0.1)
print X.toarray()

[[ 0.  0.  0.  1.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]]


In [10]:
TAGS = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']
ITEM_COUNT = 10
TAG_COUNT = len(TAGS)
DENSITY = 0.1

# X: tag matrix
# T: maximun number of questions
# GAMMA: discount factor
X = gen_rand_sparse_mat(ITEM_COUNT, TAG_COUNT, DENSITY)
T = 2
GAMMA = 0.8

print X.toarray()

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]]


In [ ]:
import numpy as np
from scipy import sparse

def questionSellectionAlgo(X, w, GAMMA):
    return 1
    
# Main algorithm: Interactive Recommandation
# Input:
#   X: tag matrix
#   T: maximun number of questions
#   GAMMA: discount factor
# Output:
#   w: an updated weight vector w^(T)
def interactiveRecommandation(X, T, GAMMA):
    w = np.ones(ITEM_COUNT)
    t = 0
    for t in range(T):
        q = questionSellectionAlgo(X, w, GAMMA)
        X_q = X.toarray()[:, q]
        print 'select', TAGS[q], ', X(q): ', X_q
        
        ans = raw_input('has ' + TAGS[q] + '? (0/1): ')
        g = np.ones(ITEM_COUNT)
        if ans == '1':
            g = X_q
        else:
            g = (1 - X_q)
        g[g == 0] = GAMMA
        w = w*g
        print 'W: ', w
    return w
    
    
interactiveRecommandation(X, T, GAMMA)

select 1 , X(q):  [ 0.  1.  0.  0.  1.  0.  0.  0.  0.  0.]
